version: "1"
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9011:9010"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@muhxv47vn6udjo78_high?TNS_ADMIN=wallet/
      - spring.datasource.username=DSY2201_S6
      - spring.datasource.password=Password1078
    restart: always